### ISSUE TITLE
Creating a file doesn't work

### ISSUE THREAD

**Issue by mathieudutour** [Lona/xd-file#1]
the format is so messy I couldn't figure out how to create a new empty file. Maybe some id references are broken or something.

**Comment by macintoshhelper** [comment]
I've tried, and had no luck, with generating a `.xd` file zip from an extracted folder. The main challenge seems to be to generate a zip with a binary format that XD expects. I've done some analysis with `zipinfo` and a number of the files are uncompressed, probably to allow XD to read metadata quickly.

Here's some sample code of mine (doesn't work, but the result zip binary is fairly close to XD's one):

```js

const archiver = require('archiver');

function zipDirectory(dir, out) {
  const inPath = path.resolve(__dirname, dir);

  const archive = archiver('zip', {
    zlib: { level: 1 }, // Sets compression level
  });

  const output = fs.createWriteStream(path.resolve(__dirname, out));

  output.on('end', function () {
    console.log('Data has been drained');
  });

  // good practice to catch this error explicitly
  archive.on('error', function (err) {
    throw err;
  });

  archive.pipe(output);

  const storePaths = [
    'mimetype',
    'META-INF/metadata.xml',
    'preview.png',
    'renditions/image-237-512.png',
    'renditions/image-375-812.png',
    'thumbnail.png',
  ];

  const paths = [
    'mimetype',
    'manifest',
    'META-INF/metadata.xml',
    'artwork/artboard-318a8fde-24a1-4043-b65e-d0920cda5c39/graphics/graphicContent.agc',
    'artwork/pasteboard/graphics/graphicContent.agc',
    'interactions/interactions.json',
    'preview.png',
    'renditions/image-237-512.png',
    'renditions/image-375-812.png',
    'resources/graphics/graphicContent.agc',
    'thumbnail.png',
  ]

  paths.forEach((storPath) => {
    const filePath = path.join(inPath, storPath);

    // Am hardcoding the files for now, as this generates unnecessary empty directories, additional to the directories with their contents. Not sure if necessary, but the original `.xd` file doesn't have them.
    if (storPath.slice(-1) === '/') {
      archive.glob(`${storPath}**/*`, {
        cwd: inPath,
        ignore: [".*"],
      }, { store: storePaths.includes(storPath), mode: 'F:0644' });
    } else {
      archive.append(fs.createReadStream(filePath), { name: storPath, store: storePaths.includes(storPath), mode: 'F:0644' });
    }
  });


   output.on('close', function () {
     console.log(archive.pointer() + ' total bytes');
     console.log('archiver has been finalized and the output file descriptor has closed.');
   });

  return archive.finalize();
}

```

Some differences of the zip my code generates, vs the XD generated zip:

- `extended local header` should be `no`
- `version of encoding software` should `0.0` maybe? Not sure how to inject the version though
- `compression sub type` should be `superfast`
- `apparent file type` should be calculated as `text` or `binary` dynamically (maybe XD will calculate this itself though)
- `offset of local header from start of archive` doesn't match up

Not sure how to set this zlib metadata with Node.js `zlib` though.

**Comment by mathieudutour** [comment]
yeah it's really weird. Haven't been able to find the code doing the encoding/decoding in the app

**Comment by macintoshhelper** [comment]
> yeah it's really weird. Haven't been able to find the code doing the encoding/decoding in the app

I seem to have solved it 🙂 (from InfoZip `zip` CLI though). `application/vnd.adobe.sparkler.project+dcxucf` seems to be based off Universal Container Format. It does appear that `extended local header` has to be `no`, and that the other attributes don't really matter much. I can't find a Node.js zip library that supports the `-X` property (`eXclude eXtra file attributes`), but using a `zip` binary should be fine for Mac, Linux and Windows (with a precompiled binary), with `require('child_process').exec`.

```sh
cd my-project/
zip -X0 ../my-project.xd mimetype # We need mimetype to be the first file and uncompressed
zip -rDX9 ./my-project.xd * -x mimetype # Compress remaining files, ignoring mimetype
```

**Reference**
- https://researchobject.github.io/specifications/bundle/2014-11-05/#h3_ucf
- https://gist.github.com/bitsgalore/da04413787931d20a8bf
- https://www.w3.org/publishing/epub/epub-ocf.html#sec-zip-container-zipreqs

**Comment by mathieudutour** [comment]
Oh nice work! I managed to write a valid xd file: https://github.com/Lona/xd-file/commit/b76e85065f117cee10db28101148287b9257126f

**Comment by macintoshhelper** [comment]
Great! Could be worth abstracting the zip manifest/contents bit into a Node.js UCF library, seems there isn't much out there for generating ePub/UCF zip files in the Node.js community. e.g. something like https://mygrid.github.io/ruby-ucf/

This lib might make a more complete version of `react-xd` possible (generate XD files with an XD API bridge, say through WebSockets, to compute text sizes, etc, and pass the JSON over to an XD file generator to setup the group nesting, etc).
